### PR TITLE
Fix upload authentication workflow

### PR DESCRIPTION
**Pull request by La0**
Hello,

I fixed an error during the Garmin upload workflow: you now need to follow the redirections in order to access another cookie.

### CODE REVIEW

**Comment by aspiers** [comment]
Oh cool, this could explain why uploads stopped working for me quite a while ago.  If I have any free time I will try to test this.  Thanks for sharing!

**Comment by frankcrawford** [comment]
@La0, @dlotton I was just about to upload a major update to the authentication section, due to upload issues I've been having.  They are based on the tapirilk code, and seems to work well for me.
However, they are significantly different from your code, in that it loops around up to six times, rather than your changes.

It would be good to see if this update fixes your problem, particularly, as it is going to be easier going forward to poach from tapirilk rather than having to track the variations ourselves.

Let me know know if you want my patch, as I haven't yet forked this repo.

**Comment by darkzbaron** [comment]
hey, im getting constantly LOGIN FAILED, is this related to this issue? Thanks for the great work,Jonathan

**Comment by frankcrawford** [comment]
It depends on what sort of login failure, but yes, I suspect that the current login process is very broken, due to changes by Garmin.

**Comment by La0** [comment]
@dlotton What's your status on the project ? Do you still maintain it ? Maybe we could create a fork that handles current authentication better.

**Comment by La0** [comment]
I just upgraded the login workflow to the last updates on Garmin servers.

@dlotton Can you merge this ?

**Comment by La0** [comment]
I close this PR, as my [fork is now online](https://github.com/La0/garmin-uploader) :smile_cat:

**Pull request closed without merging**
